// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHgnSkiB-49r1kdzoZFz4ZGX-UbLGfNI',
    appId: '1:92941073089:web:5a3976cd8e9deb84417240',
    messagingSenderId: '92941073089',
    projectId: 'new-social-app-project',
    authDomain: 'new-social-app-project.firebaseapp.com',
    storageBucket: 'new-social-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvzt5edGUR-Q76xGFzsCy5gecqoEKxtw',
    appId: '1:92941073089:android:60c62a7b0980c2bd417240',
    messagingSenderId: '92941073089',
    projectId: 'new-social-app-project',
    storageBucket: 'new-social-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAiZSVy3Wfv_DgCNHKmrYkw97qfG34Up4',
    appId: '1:92941073089:ios:fe942275f319e946417240',
    messagingSenderId: '92941073089',
    projectId: 'new-social-app-project',
    storageBucket: 'new-social-app-project.appspot.com',
    iosClientId: '92941073089-pi0qljuje6cvl30618jcfdfviea3533d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAiZSVy3Wfv_DgCNHKmrYkw97qfG34Up4',
    appId: '1:92941073089:ios:6761d6f4f297b7f7417240',
    messagingSenderId: '92941073089',
    projectId: 'new-social-app-project',
    storageBucket: 'new-social-app-project.appspot.com',
    iosClientId: '92941073089-hdtomua6nrm0ds1gnro6udckgeipr7on.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
